name: foodzi
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  drawerbehavior: ^0.0.8


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  # Http 
  http: ^0.12.0+2
  pin_code_text_field: ^1.5.1
  shared_preferences: 
  crypto:
  outline_material_icons: ^0.1.1
  image_picker:
  path_provider: 
  keyboard_actions: ^3.1.2
  geolocator: ^5.2.0 

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
      #splashscreen Images
      - assets/SplashScreen/LauncherScreen.png
      - assets/SplashScreen/LauncherScreen@2x.png
      - assets/SplashScreen/LauncherScreen@3x.png
      
      #Logo Images  
      - assets/Logo/foodzi_logo.jpg
      - assets/Logo/foodzi_logo@2x.jpg
      - assets/Logo/foodzi_logo@3x.jpg
      #Lock Images
      - assets/LockImage/Group_1560.png
      - assets/LockImage/Group_1560@2x.png
      - assets/LockImage/Group_1560@3x.png
      #Phone Images
      - assets/PhoneImage/Group_295.png
      - assets/PhoneImage/Group_295@2x.png
      - assets/PhoneImage/Group_295@3x.png
      #Landing
      - assets/LandingImage/Group1561.png
      - assets/LandingImage/Group1561@2x.png
      - assets/LandingImage/Group1561@3x.png
      #DineIn
      - assets/DineInImage/Group1504.png
      - assets/DineInImage/Group1504@2x.png
      - assets/DineInImage/Group1504@3x.png
      #TakeAway
      - assets/TakeAwayImage/Group1505.png
      - assets/TakeAwayImage/Group1505@2x.png
      - assets/TakeAwayImage/Group1505@3x.png
      #HotelImages
      - assets/HotelImages/Image12.png
      - assets/HotelImages/Image12@2x.png
      - assets/HotelImages/Image12@3x.png
      #ProfileImage
      - assets/ProfileImage/MaskGroup15.png
      - assets/ProfileImage/MaskGroup15@2x.png
      - assets/ProfileImage/MaskGroup15@3x.png
      #MenuIcon
      - assets/MenuIcon/menu.png
      - assets/MenuIcon/menu@2x.png
      - assets/MenuIcon/menu@3x.png
      #BlurImages
      - assets/BlurImage/Group1612.png
      - assets/BlurImage/Group1612@2x.png
      - assets/BlurImage/Group1612@3x.png

      #SignOutImage
      - assets/SignOutImage/Group 1349.png
      - assets/SignOutImage/Group 1349@2x.png
      - assets/SignOutImage/Group 1349@3x.png
      #DrawerBackgroundImage
      - assets/DrawerBackgroundImage/Group1649.png
      - assets/DrawerBackgroundImage/Group1649@2x.png
      - assets/DrawerBackgroundImage/Group1649@3x.png

      #BackGroundImages
      - assets/BackgroundImage/Group1649.png
      - assets/BackgroundImage/Group1649@2x.png
      - assets/BackgroundImage/Group1649@3x.png
        #SignOutIcon
      - assets/SignOutIcon/Group1349.png
      - assets/SignOutIcon/Group1349@2x.png
      - assets/SignOutIcon/Group1349@3x.png

        #HomeIcon
      - assets/HomeIcon/home(2).png
      - assets/HomeIcon/home(2)@2x.png
      - assets/HomeIcon/home(2)@3x.png
        #NotificationIcon 
      - assets/NotificationIcon/Path1159.png
      - assets/NotificationIcon/Path1159@2x.png
      - assets/NotificationIcon/Path1159@3x.png
        #OrderIcon
      - assets/OrderIcon/order.png
      - assets/OrderIcon/order@2x.png
      - assets/OrderIcon/order@3x.png
        #UserIcon
      - assets/UserIcon/Group3.png
      - assets/UserIcon/Group3@2x.png
      - assets/UserIcon/Group3@3x.png
        #LevelsIcon
      - assets/LevelsIcon/levels.png
      - assets/LevelsIcon/levels@2x.png
      - assets/LevelsIcon/levels@3x.png
      #ClockIcon
      - assets/ClockIcon/clock.png
      - assets/ClockIcon/clock@2x.png
      - assets/ClockIcon/clock@3x.png
      #BackButtonIcon
      - assets/BackButtonIcon/Path1621.png
      - assets/BackButtonIcon/Path1621@2x.png
      - assets/BackButtonIcon/Path1621@3x.png


      
      

      
      
     

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: HelveticaNeue
      fonts:
        - asset: fonts/HelveticaNeue.ttf
      


    - family: gotham
      fonts:
        - asset: fonts/gotham-book.ttf
        - asset: fonts/gotham-Light.ttf
          weight: 300
        - asset: fonts/gotham-medium.ttf
          weight: 500
        - asset: fonts/gotham-Bold.ttf
          weight: 700


    - family: SegoeUI
      fonts:
        - asset: fonts/segoe-ui.ttf
  #

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

module:
  androidX: true 
    
   
    