name: foodzi
description: A new Flutter project.

version: 3.2+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  carousel_slider:
  basic_utils: ^2.5.3

  cupertino_icons: ^0.1.2
  http: ^0.12.0+2
  pin_code_text_field: ^1.5.1
  url_launcher: ^5.4.10
  shared_preferences: ^0.5.6+3
  package_info: ^0.4.0+18

  
  crypto:

  outline_material_icons: ^0.1.1
  image_picker:
  path_provider: ^1.6.10
  keyboard_actions: ^3.1.2
  geolocator: ^5.2.0 

 
  cached_network_image: ^2.0.0
  country_code_picker: ^1.3.11
  transparent_image: ^1.0.0
  auto_size_text: ^2.1.0
  toast: ^0.1.5
  get_it: ^4.0.2


  dio: ^3.0.8
  map_launcher: ^0.4.2
  flutter_launcher_icons: ^0.7.3
  flutter_webview_plugin: ^0.3.10+1
  badges: ^1.1.0
  firebase_messaging: ^6.0.13
  progress_dialog: ^1.2.1
  flappy_search_bar: ^1.7.2
  intl: ^0.16.1
  flutter_local_notifications:


dev_dependencies:
  flutter_test:
    sdk: flutter
#APPICON 
flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/FoodZiIcon/food_app_icon.png"

flutter:

  uses-material-design: true

  assets:
      #Splashscreen Images
      - assets/SplashScreen/LauncherScreen.png
      - assets/SplashScreen/LauncherImg.png
      - assets/faq.json
      #Logo Images  
      - assets/Logo/foodzi_logo.png
      #Lock Images
      - assets/LockImage/Group_1560.png
      - assets/LockImage/Group_1560@2x.png
      - assets/LockImage/Group_1560@3x.png
      #Phone Images
      - assets/PhoneImage/Group_295.png
      - assets/PhoneImage/Group_295@2x.png
      - assets/PhoneImage/Group_295@3x.png
      #Landing
      - assets/LandingImage/Group1561.png
      - assets/LandingImage/Group1561@2x.png
      - assets/LandingImage/Group1561@3x.png
      #DineIn
      - assets/DineInImage/Group1504.png
      - assets/DineInImage/Group1504@2x.png
      - assets/DineInImage/Group1504@3x.png
      #TakeAway
      - assets/TakeAwayImage/Group1505.png
      - assets/TakeAwayImage/Group1505@2x.png
      - assets/TakeAwayImage/Group1505@3x.png
      #HotelImages
      - assets/HotelImages/Image12.png
      - assets/HotelImages/Image12@2x.png
      - assets/HotelImages/Image12@3x.png
      - assets/HotelImages/MaskGroup20.png
      - assets/HotelImages/Image31.png
      #ProfileImage
      - assets/ProfileImage/MaskGroup15.png
      - assets/ProfileImage/MaskGroup15@2x.png
      - assets/ProfileImage/MaskGroup15@3x.png
      #MenuIcon
      - assets/MenuIcon/menu.png
      - assets/MenuIcon/menu@2x.png
      - assets/MenuIcon/menu@3x.png
      #BlurImages
      - assets/BlurImage/Group1612.png
      - assets/BlurImage/Group1612@2x.png
      - assets/BlurImage/Group1612@3x.png

      #SignOutImage
      - assets/SignOutImage/Group 1349.png
      - assets/SignOutImage/Group 1349@2x.png
      - assets/SignOutImage/Group 1349@3x.png
      #DrawerBackgroundImage
      - assets/DrawerBackgroundImage/Group1649.png
      - assets/DrawerBackgroundImage/Group1649@2x.png
      - assets/DrawerBackgroundImage/Group1649@3x.png

      #BackGroundImages
      - assets/BackgroundImage/Group1649.png
      - assets/BackgroundImage/Group1649@2x.png
      - assets/BackgroundImage/Group1649@3x.png
        #SignOutIcon
      - assets/SignOutIcon/Group1349.png
      - assets/SignOutIcon/Group1349@2x.png
      - assets/SignOutIcon/Group1349@3x.png

        #HomeIcon
      - assets/HomeIcon/home(2).png
      - assets/HomeIcon/home(2)@2x.png
      - assets/HomeIcon/home(2)@3x.png
        #NotificationIcon 
      - assets/NotificationIcon/Path1159.png
      - assets/NotificationIcon/Path1159@2x.png
      - assets/NotificationIcon/Path1159@3x.png
        #OrderIcon
      - assets/OrderIcon/order.png
      - assets/OrderIcon/order@2x.png
      - assets/OrderIcon/order@3x.png
        #UserIcon
      - assets/UserIcon/Group3.png
      - assets/UserIcon/Group3@2x.png
      - assets/UserIcon/Group3@3x.png
        #LevelsIcon
      - assets/LevelsIcon/levels.png
      - assets/LevelsIcon/levels@2x.png
      - assets/LevelsIcon/levels@3x.png
      #ClockIcon
      - assets/ClockIcon/clock.png
      - assets/ClockIcon/clock@2x.png
      - assets/ClockIcon/clock@3x.png
      #BackButtonIcon
      - assets/BackButtonIcon/Path1621.png
      - assets/BackButtonIcon/Path1621@2x.png
      - assets/BackButtonIcon/Path1621@3x.png
      #PlaceholderImage
      - assets/PlaceholderImage/placeholder.png
      #Navigate Button
      - assets/NavigateButton/next(2).png
      - assets/NavigateButton/next(2)@2x.png
      - assets/NavigateButton/next(2)@3x.png
      #PlaceHolder food image
      - assets/PlaceholderFoodImage/MaskGroup55.png
      - assets/PlaceholderFoodImage/MaskGroup55@2x.png
      - assets/PlaceholderFoodImage/MaskGroup55@3x.png
      #SuccessImage
      - assets/SuccessIcon/success.png
      - assets/SuccessIcon/success@2x.png
      - assets/SuccessIcon/success@3x.png
      #SuccessImage
      - assets/VegIcon/Group1661.png
      - assets/VegIcon/Group1661@2x.png
      - assets/VegIcon/Group1661@3x.png
      

  fonts:
    - family: HelveticaNeue
      fonts:
        - asset: fonts/HelveticaNeue.ttf
      


    - family: gotham
      fonts:
        - asset: fonts/gotham-book.ttf
        - asset: fonts/gotham-Light.ttf
          weight: 300
        - asset: fonts/gotham-medium.ttf
          weight: 500
        - asset: fonts/gotham-Bold.ttf
          weight: 700


    - family: SegoeUI
      fonts:
        - asset: fonts/segoe-ui.ttf
  


module:
  androidX: true